### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by SirFreddie** [kibook/redm-weathersync#1]
Why am i getting the Access denied message if im admin?

**Comment by kibook** [comment]
Which commands give you that message? Check that you have the right aces for command.weather, command.time, etc. Typically, server.cfg will contain something like the following:
```
add_ace group.admin command allow
```
which grants members of group.admin access to all commands by default, but you can check that that has indeed been set using the `list_aces` command, and also whether you are in the correct group with the `list_principals` command.
